### ISSUE TITLE
stocker les référentiels et autres sources de données et les DL par API plutôt que de les pousser dans l'app 

### ISSUE THREAD

**Issue by phileas-condemine** [indsante/dico-snds#3]
Ca évitera de devoir repousser l'app entière, on ira seulement mettre à jour les tables sous-jacentes

**Comment by phileas-condemine** [comment]
Une piste pour rester sur postgres https://www.cybertec-postgresql.com/en/visualizing-data-in-postgresql-with-r-shiny/

**Comment by strayMat** [comment]
Bonne idée, je pense qu'à terme il est préférable d'avoir plutôt des DBs que des Csvs, notamment pour les nomenclatures qui sont l'élément le plus varaibale de notre app.

Mais si l'on choisit cette solution, il va falloir héberger la DB quelquepart ? Sur quel serveur ? 
Matthieu

**Comment by phileas-condemine** [comment]
J'ai deux stratégies en tête à court terme : 
- https://www.elephantsql.com/
- VM de l'incubateur des ministères sociaux sur laquelle (par exemple celle sur laquelle tourne notre OSRM interne) on installerait Docker et Postgres et on demanderait aux admins d'exposer notre port 5432 sur une adresse du genre dico-snds.num.social.gouv.fr

**Comment by strayMat** [comment]
Pour le moment, nous n'avons pas de cas d'usage précis qui justifierait l'utilisation d'une BdD (plus lourde et moins accessible pour les contributeurs extérieurs que les csv actuels). 

Je ferme l'issue pour le moment, on la rouvrira si un de ces cas d'usage apparaît.
