### ISSUE TITLE
valeurs de bio_prs_ide ne s'affichent pas

### ISSUE THREAD

**Issue by claireleboucher** [indsante/dico-snds#4]
quand on essaye les valeurs de bio_prs_ide (par la table er_bio_f) on a le message d'erreur suivant :
Variable BIO_PRS_IDE
An error has occurred. Check your logs or contact the app author for clarification.

**Comment by strayMat** [comment]
Merci pour cette remarque, il nous manquait effectivement le réferentiel IR_BIO_R.

Nous l'avons récupéré [sur le site amélie.fr à cette adresse ](http://www.codage.ext.cnamts.fr/codif/nabm/index_presentation.php?p_site=AMELI) comme recommandé par [le wiki sniiram](http://open-data-assurance-maladie.ameli.fr/wiki-sniiram/index.php/ER_BIO_F).
Nous l'avons versé tel quel dans l'application car ce fichier avait l'air utilisable directement. 
Le bug devrait être résolu d'ici un ou deux jour, le temps d'être revu par un autre collègue.

Merci pour votre participation! Je ferme l'issue !
